# Action to install the Telink Zigbee SDK.
#
# TODO:
# - Hard-code more paths since we cannot guarentee anything if things move!
name: 'Install Telink Zigbee SDK'
description: 'Install the Zigbee SDK required to build Telink tlsr825x projects'

# env: Not valid here - see first 'step' below.

inputs:
  telink_zigbee_sdk_path:
    description: 'Directory into which to install the Zigbee SDK'
  telink_zigbee_sdk_uri:
    description: 'URI from which to download the Telink ZigBee SDK'
  telink_zigbee_sdk_zip:
    description: 'ZIPfile containing the Telink ZigBee SDK'
  telink_zigbee_sdk_hash:
    description: 'SHA256 hash to validate the integrity of the downloaded SDK'
  debug:
    description: 'Debug flag'

runs:
  using: "composite"
  steps:
    - name: Run the installer script
      shell: pwsh
      run: |
        $DebugFlag = $False
        if ( "${{ inputs.debug }}" -ieq "true" )
        {
          $DebugFlag = $True
        }
        $ShellScript="${env:GITHUB_ACTION_PATH}\install-TelinkZigBeeSdk.ps1"
        # TODO: Change the variable names and the script expectations.
        $Arguments=@{
          TelinkZigBeeSdkPath = "${{ inputs.telink_zigbee_sdk_path }}"
          TelinkZigBeeSdkUri = "${{ inputs.telink_zigbee_sdk_uri }}"
          TelinkZigBeeSdkZip = "${{ inputs.telink_zigbee_sdk_zip }}"
          TelinkZigBeeSdkHash = "${{ inputs.telink_zigbee_sdk_hash }}"
          Debug = $DebugFlag
        }
        & $ShellScript @Arguments

