

# Action to install the Telink Eclipse based IDE.
#
# TODO:
# - Hard-code more paths since we cannot guarentee anything if things move!
name: 'Install Telink IDE'
description: 'Install the Eclipse based IDE required to build Telink tlsr825x projects'

# env:  Not allowed here; see the first step below.

inputs:
  telink_ide_path:
    description: 'Directory into which to install the IDE'
  telink_ide_uri:
    description: 'URI from which to download the IDE'
  telink_ide_zip:
    description: 'Name of the ZIPfile containing the IDE'
  telink_ide_hash:
    description: 'SHA256 that can be used to validate the integrity of the downloaded IDE'
  debug:
    description: 'Debug flag'

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: pwsh
      run: |
        $ShellScript="${env:GITHUB_ACTION_PATH}\install-TelinkIde.ps1"
        $Arguments=@{
          TelinkIdePath = "${{ inputs.telink_ide_path }}"
          TelinkIdeUri = "${{ inputs.telink_ide_uri }}"
          TelinkIdeZip = "${{ inputs.telink_ide_zip }}"
          TelinkIdeHash = "${{ inputs.telink_ide_hash }}"
          Debug = "${{ inputs.debug }}"
        }
        & $ShellScript @Arguments
