on:
  push:
    paths:
      - '.github/workflows/esp32*'
      - 'actions/espressif/**'
      - 'actions/common/**'
      - 'esp32/**'
    branches:
      - '**'
    tags:
      - '*'

jobs:
  espressif-ESP32-build:
    runs-on: ubuntu-latest
    name: Testing Espressif Docker image generation.
    steps:
      # Check tag has correct syntax.
      - if: github.ref_type == 'tag'
        uses: ./actions/common/semver
        with:
          tag: $GITHUB_TAG    
          
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout required files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            actions
            esp32

      - if: github.ref_type == 'tag'
        name: Set firmware appplication version
        id: set-firmware-app-version
        shell: bash
        run: |
          sed --in-place s/\"0.0.0\"/\"${GITHUB_REF_NAME}\"/ esp32/cloudsmets/CMakeLists.txt

      - id: build-esp32-image
        name: Build the ESP32 image
        uses: ./actions/espressif/esp32/build
        with:
          project: esp32/cloudsmets

      - if: github.ref_type == 'tag'
        id: prepare-for-blob-upload
        name: Prepare firmware for upload to Azure blob storage
        shell: bash
        run: |
          mkdir _azure.upload
          cp esp32/cloudsmets/build/cloudsmets.bin _azure.upload
          cp esp32/cloudsmets/build/cloudsmets.elf _azure.upload
          cp esp32/cloudsmets/build/cloudsmets.map _azure.upload

      - if: github.ref_type == 'tag'
        name: Upload firmware to Azure blob storage
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'
          container: 'cloudsmets'
          name: '${{ github.ref_name }}'
          path: '_azure.upload'

      - uses: actions/upload-artifact@v3
        name: Upload firmware to GitHub artifacts storage
        with:
          name: esp32-firmware
          path: |
            esp32/cloudsmets/build/cloudsmets.bin
            esp32/cloudsmets/build/cloudsmets.elf
            esp32/cloudsmets/build/cloudsmets.map
          retention-days: 1
          if-no-files-found: error

