on:
  push:
    paths:
      - '.github/workflows/tlsr825x*'
      - 'actions/telink/**'
      - 'tlsr8258/**'
    branches:
      - '**'
    tags-ignore:
      # Without this, tagged builds always trigger this workflow and right now
      # there is no need for that since we don't have a tlsr8258 image worth
      # tagging and saving.
      - '*'

jobs:
  TeLink-tlsr825x-build:
    runs-on: windows-latest
    name: Test install of the TLSR825x build environment and image build.
    steps:
        - name: set-env-vars
          shell: pwsh
          run: |
            echo "TELINK_IDE_PATH=${env:GITHUB_WORKSPACE}\_ide" >> ${env:GITHUB_ENV}

            # The _PATH is the place we install to.
            echo "TELINK_ZIGBEE_SDK_PATH=${env:GITHUB_WORKSPACE}\_sdk" >> ${env:GITHUB_ENV}
            echo "TELINK_ZIGBEE_SDK=${env:GITHUB_WORKSPACE}\_sdk\tl_zigbee_sdk" >> ${env:GITHUB_ENV}

        - uses: actions/checkout@v3
          with:
            sparse-checkout: |
              .github
              actions
              tlsr8258

        - id: install-ide
          uses: ./actions/telink/tlsr825x/install-ide
          with:
            telink_ide_path: ${{ env.TELINK_IDE_PATH }}
            TRY_ME: ${{ var.TRY_ME }}

        - id: install-zigbee-sdk
          uses: ./actions/telink/tlsr825x/install-tl-zigbee-sdk
          with:
            telink_zigbee_sdk_path: ${{ env.TELINK_ZIGBEE_SDK_PATH }}

        - id: build-tlsr825x-image
          uses: ./actions/telink/tlsr825x/build
          with:
            telink_ide_path: ${{ env.TELINK_IDE_PATH }}
            telink_zigbee_sdk: ${{ env.TELINK_ZIGBEE_SDK }}

