on:
  push:
    paths:
      - '.github/workflows/tlsr825x*'
      - 'actions/telink/**'
      - 'tlsr8258/**'
    branches:
      - '**'
    tags-ignore:
      # Without this, tagged builds always trigger this workflow and right now
      # there is no need for that since we don't have a tlsr8258 image worth
      # tagging and saving.
      - '*'

env:
  # Locations where we will install the required software.
  TELINK_ZIGBEE_SDK_PATH: ${GITHUB_WORKSPACE}\_sdk"
  TELINK_IDE_PATH: ${GITHUB_WORKSPACE}\_ide

  SDK_URI: "http://wiki.telink-semi.cn/tools_and_sdk/Zigbee/Zigbee_SDK.zip"
  SDK_ZIP: Zigbee_SDK.zip
  SDK_HASH: "AD3C28FC2A50E9D550B933335FD96CE2A58EECDD602DEB451FCC54087947E01C"

jobs:
  TeLink-tlsr825x-build:
    runs-on: windows-latest
    name: Test install of the TLSR825x build environment and image build.
    steps:
        - uses: actions/checkout@v3
          with:
            sparse-checkout: |
              .github
              actions
              tlsr8258

        - id: install-ide
          uses: ./actions/telink/tlsr825x/install-ide
          with:
            telink_ide_path: ${TELINK_IDE_PATH}

        - id: install-zigbee-sdk
          uses: ./actions/telink/tlsr825x/install-tl-zigbee-sdk
          with:
            telink_zigbee_sdk_path: ${TELINK_ZIGBEE_SDK_PATH}

        - id: build-tlsr825x-image
          uses: ./actions/telink/tlsr825x/build
          with:
            telink_ide_path: ${TELINK_IDE_PATH}
            telink_zigbee_sdk_path: ${TELINK_ZIGBEE_SDK_PATH}

